export const SONG_CATALOG = [
  { id: 1, title: 'Sunrise City', artist: 'Neon Echo', genre: 'pop', mood: 'happy', energy: 0.82, tempoBpm: 118, valence: 0.84, danceability: 0.79, acousticness: 0.18 },
  { id: 2, title: 'Midnight Coding', artist: 'LoRoom', genre: 'lofi', mood: 'chill', energy: 0.42, tempoBpm: 78, valence: 0.56, danceability: 0.62, acousticness: 0.71 },
  { id: 3, title: 'Storm Runner', artist: 'Voltline', genre: 'rock', mood: 'intense', energy: 0.91, tempoBpm: 152, valence: 0.48, danceability: 0.66, acousticness: 0.1 },
  { id: 4, title: 'Library Rain', artist: 'Paper Lanterns', genre: 'lofi', mood: 'chill', energy: 0.35, tempoBpm: 72, valence: 0.6, danceability: 0.58, acousticness: 0.86 },
  { id: 5, title: 'Gym Hero', artist: 'Max Pulse', genre: 'pop', mood: 'intense', energy: 0.93, tempoBpm: 132, valence: 0.77, danceability: 0.88, acousticness: 0.05 },
  { id: 6, title: 'Spacewalk Thoughts', artist: 'Orbit Bloom', genre: 'ambient', mood: 'chill', energy: 0.28, tempoBpm: 60, valence: 0.65, danceability: 0.41, acousticness: 0.92 },
  { id: 7, title: 'Coffee Shop Stories', artist: 'Slow Stereo', genre: 'jazz', mood: 'relaxed', energy: 0.37, tempoBpm: 90, valence: 0.71, danceability: 0.54, acousticness: 0.89 },
  { id: 8, title: 'Night Drive Loop', artist: 'Neon Echo', genre: 'synthwave', mood: 'moody', energy: 0.75, tempoBpm: 110, valence: 0.49, danceability: 0.73, acousticness: 0.22 },
  { id: 9, title: 'Focus Flow', artist: 'LoRoom', genre: 'lofi', mood: 'focused', energy: 0.4, tempoBpm: 80, valence: 0.59, danceability: 0.6, acousticness: 0.78 },
  { id: 10, title: 'Rooftop Lights', artist: 'Indigo Parade', genre: 'indie pop', mood: 'happy', energy: 0.76, tempoBpm: 124, valence: 0.81, danceability: 0.82, acousticness: 0.35 },
  { id: 11, title: 'Golden Hour Drift', artist: 'Velvet Theory', genre: 'r&b', mood: 'romantic', energy: 0.58, tempoBpm: 95, valence: 0.78, danceability: 0.71, acousticness: 0.45 },
  { id: 12, title: 'Circuit Breaker', artist: 'Static Bloom', genre: 'electronic', mood: 'energetic', energy: 0.88, tempoBpm: 140, valence: 0.62, danceability: 0.92, acousticness: 0.03 },
  { id: 13, title: 'Rainy Window', artist: 'Clara Moss', genre: 'folk', mood: 'melancholic', energy: 0.25, tempoBpm: 68, valence: 0.22, danceability: 0.38, acousticness: 0.94 },
  { id: 14, title: 'Kingdom Come', artist: 'Hex Royal', genre: 'hip-hop', mood: 'confident', energy: 0.8, tempoBpm: 105, valence: 0.68, danceability: 0.87, acousticness: 0.12 },
  { id: 15, title: 'Ember and Ash', artist: 'Iron Cult', genre: 'metal', mood: 'angry', energy: 0.97, tempoBpm: 168, valence: 0.3, danceability: 0.55, acousticness: 0.04 },
  { id: 16, title: 'Moonlit Serenade', artist: 'Ivory Keys', genre: 'classical', mood: 'peaceful', energy: 0.18, tempoBpm: 58, valence: 0.7, danceability: 0.28, acousticness: 0.98 },
  { id: 17, title: 'Salsa Roja', artist: 'La Llama', genre: 'latin', mood: 'uplifting', energy: 0.85, tempoBpm: 128, valence: 0.9, danceability: 0.94, acousticness: 0.2 },
  { id: 18, title: 'Slow Burn Summer', artist: 'Dusk Quartet', genre: 'soul', mood: 'nostalgic', energy: 0.52, tempoBpm: 88, valence: 0.63, danceability: 0.66, acousticness: 0.52 },
  { id: 19, title: 'Quiet Constellations', artist: 'Mira Vale', genre: 'ambient', mood: 'peaceful', energy: 0.2, tempoBpm: 62, valence: 0.58, danceability: 0.34, acousticness: 0.9 },
  { id: 20, title: 'Notebook Daydream', artist: 'Sunday Static', genre: 'lofi', mood: 'focused', energy: 0.33, tempoBpm: 74, valence: 0.61, danceability: 0.57, acousticness: 0.82 },
  { id: 21, title: 'Electric Sidewalk', artist: 'Nova Arcade', genre: 'electronic', mood: 'energetic', energy: 0.9, tempoBpm: 136, valence: 0.74, danceability: 0.91, acousticness: 0.06 },
  { id: 22, title: 'Weekend Confetti', artist: 'Peach Radio', genre: 'pop', mood: 'happy', energy: 0.84, tempoBpm: 126, valence: 0.91, danceability: 0.86, acousticness: 0.14 },
  { id: 23, title: 'Velvet Thunder', artist: 'Northbound', genre: 'rock', mood: 'intense', energy: 0.89, tempoBpm: 148, valence: 0.43, danceability: 0.59, acousticness: 0.11 },
  { id: 24, title: 'Blue Hour Letters', artist: 'June Harbor', genre: 'indie pop', mood: 'moody', energy: 0.47, tempoBpm: 96, valence: 0.36, danceability: 0.63, acousticness: 0.55 },
  { id: 25, title: 'Window Seat', artist: 'Maple Cinema', genre: 'folk', mood: 'nostalgic', energy: 0.3, tempoBpm: 76, valence: 0.52, danceability: 0.45, acousticness: 0.91 },
  { id: 26, title: 'Afterglow Avenue', artist: 'Rose Meridian', genre: 'r&b', mood: 'romantic', energy: 0.6, tempoBpm: 98, valence: 0.76, danceability: 0.75, acousticness: 0.39 },
  { id: 27, title: 'Golden Sneakers', artist: 'Daylight Club', genre: 'funk', mood: 'uplifting', energy: 0.79, tempoBpm: 116, valence: 0.93, danceability: 0.93, acousticness: 0.16 },
  { id: 28, title: 'Deep Work', artist: 'Analog Garden', genre: 'lofi', mood: 'focused', energy: 0.38, tempoBpm: 80, valence: 0.54, danceability: 0.56, acousticness: 0.8 },
  { id: 29, title: 'Paper Moons', artist: 'Low Tide', genre: 'dream pop', mood: 'chill', energy: 0.41, tempoBpm: 84, valence: 0.57, danceability: 0.61, acousticness: 0.68 },
  { id: 30, title: 'Fast Forward', artist: 'Prism Rush', genre: 'pop', mood: 'energetic', energy: 0.94, tempoBpm: 142, valence: 0.83, danceability: 0.89, acousticness: 0.04 },
  { id: 31, title: 'Neon Weather', artist: 'Satellite Youth', genre: 'synthwave', mood: 'moody', energy: 0.71, tempoBpm: 108, valence: 0.44, danceability: 0.72, acousticness: 0.2 },
  { id: 32, title: 'Open Window Morning', artist: 'Cedar & Sky', genre: 'acoustic', mood: 'happy', energy: 0.46, tempoBpm: 92, valence: 0.86, danceability: 0.51, acousticness: 0.93 },
  { id: 33, title: 'No Signal', artist: 'Concrete Bloom', genre: 'hip-hop', mood: 'confident', energy: 0.81, tempoBpm: 104, valence: 0.69, danceability: 0.88, acousticness: 0.1 },
  { id: 34, title: 'Soft Landing', artist: 'Cloud Assembly', genre: 'ambient', mood: 'chill', energy: 0.24, tempoBpm: 64, valence: 0.64, danceability: 0.39, acousticness: 0.94 },
  { id: 35, title: 'City in Bloom', artist: 'Color Theory', genre: 'indie pop', mood: 'uplifting', energy: 0.72, tempoBpm: 120, valence: 0.88, danceability: 0.8, acousticness: 0.3 },
  { id: 36, title: 'Last Train Home', artist: 'Amber Lines', genre: 'soul', mood: 'melancholic', energy: 0.43, tempoBpm: 82, valence: 0.31, danceability: 0.57, acousticness: 0.66 },
]
