export const SONG_CATALOG = [
  { id: 1, title: 'Sunrise City', artist: 'Neon Echo', genre: 'pop', mood: 'happy', energy: 0.82, tempoBpm: 118, valence: 0.84, danceability: 0.79, acousticness: 0.18 },
  { id: 2, title: 'Midnight Coding', artist: 'LoRoom', genre: 'lofi', mood: 'chill', energy: 0.42, tempoBpm: 78, valence: 0.56, danceability: 0.62, acousticness: 0.71 },
  { id: 3, title: 'Storm Runner', artist: 'Voltline', genre: 'rock', mood: 'intense', energy: 0.91, tempoBpm: 152, valence: 0.48, danceability: 0.66, acousticness: 0.1 },
  { id: 4, title: 'Library Rain', artist: 'Paper Lanterns', genre: 'lofi', mood: 'chill', energy: 0.35, tempoBpm: 72, valence: 0.6, danceability: 0.58, acousticness: 0.86 },
  { id: 5, title: 'Gym Hero', artist: 'Max Pulse', genre: 'pop', mood: 'intense', energy: 0.93, tempoBpm: 132, valence: 0.77, danceability: 0.88, acousticness: 0.05 },
  { id: 6, title: 'Spacewalk Thoughts', artist: 'Orbit Bloom', genre: 'ambient', mood: 'chill', energy: 0.28, tempoBpm: 60, valence: 0.65, danceability: 0.41, acousticness: 0.92 },
  { id: 7, title: 'Coffee Shop Stories', artist: 'Slow Stereo', genre: 'jazz', mood: 'relaxed', energy: 0.37, tempoBpm: 90, valence: 0.71, danceability: 0.54, acousticness: 0.89 },
  { id: 8, title: 'Night Drive Loop', artist: 'Neon Echo', genre: 'synthwave', mood: 'moody', energy: 0.75, tempoBpm: 110, valence: 0.49, danceability: 0.73, acousticness: 0.22 },
  { id: 9, title: 'Focus Flow', artist: 'LoRoom', genre: 'lofi', mood: 'focused', energy: 0.4, tempoBpm: 80, valence: 0.59, danceability: 0.6, acousticness: 0.78 },
  { id: 10, title: 'Rooftop Lights', artist: 'Indigo Parade', genre: 'indie pop', mood: 'happy', energy: 0.76, tempoBpm: 124, valence: 0.81, danceability: 0.82, acousticness: 0.35 },
  { id: 11, title: 'Golden Hour Drift', artist: 'Velvet Theory', genre: 'r&b', mood: 'romantic', energy: 0.58, tempoBpm: 95, valence: 0.78, danceability: 0.71, acousticness: 0.45 },
  { id: 12, title: 'Circuit Breaker', artist: 'Static Bloom', genre: 'electronic', mood: 'energetic', energy: 0.88, tempoBpm: 140, valence: 0.62, danceability: 0.92, acousticness: 0.03 },
  { id: 13, title: 'Rainy Window', artist: 'Clara Moss', genre: 'folk', mood: 'melancholic', energy: 0.25, tempoBpm: 68, valence: 0.22, danceability: 0.38, acousticness: 0.94 },
  { id: 14, title: 'Kingdom Come', artist: 'Hex Royal', genre: 'hip-hop', mood: 'confident', energy: 0.8, tempoBpm: 105, valence: 0.68, danceability: 0.87, acousticness: 0.12 },
  { id: 15, title: 'Ember and Ash', artist: 'Iron Cult', genre: 'metal', mood: 'angry', energy: 0.97, tempoBpm: 168, valence: 0.3, danceability: 0.55, acousticness: 0.04 },
  { id: 16, title: 'Moonlit Serenade', artist: 'Ivory Keys', genre: 'classical', mood: 'peaceful', energy: 0.18, tempoBpm: 58, valence: 0.7, danceability: 0.28, acousticness: 0.98 },
  { id: 17, title: 'Salsa Roja', artist: 'La Llama', genre: 'latin', mood: 'uplifting', energy: 0.85, tempoBpm: 128, valence: 0.9, danceability: 0.94, acousticness: 0.2 },
  { id: 18, title: 'Slow Burn Summer', artist: 'Dusk Quartet', genre: 'soul', mood: 'nostalgic', energy: 0.52, tempoBpm: 88, valence: 0.63, danceability: 0.66, acousticness: 0.52 },
]
